//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MissionPlanner {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MissionPlanner.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Advanced Params과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AdvancedParams {
            get {
                return ResourceManager.GetString("AdvancedParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to upload 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AreYouSureYouWantToUpload {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto WP과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AutoWP {
            get {
                return ResourceManager.GetString("AutoWP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bad KML File :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Bad_KML_File {
            get {
                return ResourceManager.GetString("Bad_KML_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bad Vision Position과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Bad_Vision_Position {
            get {
                return ResourceManager.GetString("Bad_Vision_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bad Accel Health과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BadAccelHealth {
            get {
                return ResourceManager.GetString("BadAccelHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bad AHRS과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BadAHRS {
            get {
                return ResourceManager.GetString("BadAHRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bad Baro Health과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BadBaroHealth {
            get {
                return ResourceManager.GetString("BadBaroHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bad Compass Health과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BadCompassHealth {
            get {
                return ResourceManager.GetString("BadCompassHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bad Lat/Lng과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BadCoords {
            get {
                return ResourceManager.GetString("BadCoords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bad GPS Signal Health과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BadGPSHealth {
            get {
                return ResourceManager.GetString("BadGPSHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bad Gyro Health과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BadGyroHealth {
            get {
                return ResourceManager.GetString("BadGyroHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bad LiDAR Health과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BadLiDARHealth {
            get {
                return ResourceManager.GetString("BadLiDARHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bad Logging과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BadLogging {
            get {
                return ResourceManager.GetString("BadLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bad OptFlow Health과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BadOptFlowHealth {
            get {
                return ResourceManager.GetString("BadOptFlowHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bad or No Terrain Data과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BadorNoTerrainData {
            get {
                return ResourceManager.GetString("BadorNoTerrainData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Basic Tuning과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BasicTuning {
            get {
                return ResourceManager.GetString("BasicTuning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Beta과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Beta {
            get {
                return ResourceManager.GetString("Beta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   These are beta firmware, use at your own risk!!!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BetaWarning {
            get {
                return ResourceManager.GetString("BetaWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not connect to com port and detect board type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CanNotConnectToComPortAnd {
            get {
                return ResourceManager.GetString("CanNotConnectToComPortAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot graph this field과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CannotGraphField {
            get {
                return ResourceManager.GetString("CannotGraphField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cant detect your Board version. Please check your cabling과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CantDetectBoardVersion {
            get {
                return ResourceManager.GetString("CantDetectBoardVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change Throttle과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ChangeThrottle {
            get {
                return ResourceManager.GetString("ChangeThrottle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Checking 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Checking {
            get {
                return ResourceManager.GetString("Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check port settings or Port in use?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CheckPortSettingsOr {
            get {
                return ResourceManager.GetString("CheckPortSettingsOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click when Done과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Click_when_Done {
            get {
                return ResourceManager.GetString("Click_when_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The Command failed to execute
        ///과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CommandFailed {
            get {
                return ResourceManager.GetString("CommandFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Communication Error - no connection과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CommunicationErrorNoConnection {
            get {
                return ResourceManager.GetString("CommunicationErrorNoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   compass variance과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string compass_variance {
            get {
                return ResourceManager.GetString("compass_variance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Completed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connect과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CONNECT과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CONNECTc {
            get {
                return ResourceManager.GetString("CONNECTc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connect Failed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ConnectFailed {
            get {
                return ResourceManager.GetString("ConnectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connecting Mavlink과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ConnectingMavlink {
            get {
                return ResourceManager.GetString("ConnectingMavlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Continue과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Converting bin to log과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Converting_bin_to_log {
            get {
                return ResourceManager.GetString("Converting_bin_to_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Description: 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Desc {
            get {
                return ResourceManager.GetString("Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Detected a 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DetectedA {
            get {
                return ResourceManager.GetString("DetectedA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Detecting Board Version과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DetectingBoardVersion {
            get {
                return ResourceManager.GetString("DetectingBoardVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disconnect과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DISCONNECT과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DISCONNECTc {
            get {
                return ResourceManager.GetString("DISCONNECTc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to load this into the flight data screen?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Do_you_want_to_load_this_into_the_flight_data_screen {
            get {
                return ResourceManager.GetString("Do_you_want_to_load_this_into_the_flight_data_screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Done과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Downloaded from internet과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DownloadedFromInternet {
            get {
                return ResourceManager.GetString("DownloadedFromInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Downloading from Internet과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DownloadingFromInternet {
            get {
                return ResourceManager.GetString("DownloadingFromInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ensure your props are not on the Plane/Quad과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EnsurePropsNotOn {
            get {
                return ResourceManager.GetString("EnsurePropsNotOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Epprom changed, all your setting will be lost during the update,
        ///Do you wish to continue?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EppromChanged {
            get {
                return ResourceManager.GetString("EppromChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Epprom format changed ({0) vs {1})과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EppromFormatChanged {
            get {
                return ResourceManager.GetString("EppromFormatChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error binding과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_binding {
            get {
                return ResourceManager.GetString("Error_binding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error closing log files과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ErrorClosingLogFile {
            get {
                return ResourceManager.GetString("ErrorClosingLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error communicating with the autopilot과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ErrorCommunicating {
            get {
                return ResourceManager.GetString("ErrorCommunicating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error Connecting
        ///과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ErrorConnecting {
            get {
                return ResourceManager.GetString("ErrorConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This feature is not enabled in your firmware.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ErrorFeatureNotEnabled {
            get {
                return ResourceManager.GetString("ErrorFeatureNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error loading firmware file과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ErrorFirmwareFile {
            get {
                return ResourceManager.GetString("ErrorFirmwareFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error receiving log list과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ErrorLogList {
            get {
                return ResourceManager.GetString("ErrorLogList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error: no responce from MAV과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ErrorNoResponce {
            get {
                return ResourceManager.GetString("ErrorNoResponce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You are not connected.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ErrorNotConnected {
            get {
                return ResourceManager.GetString("ErrorNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error receiving list
        ///과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ErrorReceivingParams {
            get {
                return ResourceManager.GetString("ErrorReceivingParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error: command rejected by MAV과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ErrorRejectedByMAV {
            get {
                return ResourceManager.GetString("ErrorRejectedByMAV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error renaming file과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ErrorRenameFile {
            get {
                return ResourceManager.GetString("ErrorRenameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error setting parameter 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ErrorSettingParameter {
            get {
                return ResourceManager.GetString("ErrorSettingParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set {0} Failed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ErrorSetValueFailed {
            get {
                return ResourceManager.GetString("ErrorSetValueFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error uploading firmware과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ErrorUploadingFirmware {
            get {
                return ResourceManager.GetString("ErrorUploadingFirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extended Tuning과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExtendedTuning {
            get {
                return ResourceManager.GetString("ExtendedTuning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to create ground station log - wont log this session과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Failclog {
            get {
                return ResourceManager.GetString("Failclog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to connect to SITL instance과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Failed_to_connect_to_SITL_instance {
            get {
                return ResourceManager.GetString("Failed_to_connect_to_SITL_instance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to download the SITL image.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Failed_to_download_the_SITL_image {
            get {
                return ResourceManager.GetString("Failed_to_download_the_SITL_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed download과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FailedDownload {
            get {
                return ResourceManager.GetString("FailedDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed read HEX과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FailedReadHEX {
            get {
                return ResourceManager.GetString("FailedReadHEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to read firmware.hex :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FailedToReadHex {
            get {
                return ResourceManager.GetString("FailedToReadHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed upload과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FailedUpload {
            get {
                return ResourceManager.GetString("FailedUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FailSafe과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FailSafe {
            get {
                return ResourceManager.GetString("FailSafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Flight Modes과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FlightModes {
            get {
                return ResourceManager.GetString("FlightModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Full Parameter List과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FullParameterList {
            get {
                return ResourceManager.GetString("FullParameterList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Full Parameter Tree과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FullParameterTree {
            get {
                return ResourceManager.GetString("FullParameterTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GeoFence과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GeoFence {
            get {
                return ResourceManager.GetString("GeoFence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Geofence Breach과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GeofenceBreach {
            get {
                return ResourceManager.GetString("GeofenceBreach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Getting 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Getting {
            get {
                return ResourceManager.GetString("Getting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Getting FW List과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GettingFWList {
            get {
                return ResourceManager.GetString("GettingFWList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Getting FW Version과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GettingFWVersion {
            get {
                return ResourceManager.GetString("GettingFWVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Getting Params과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GettingParams {
            get {
                return ResourceManager.GetString("GettingParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Getting Params...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GettingParamsD {
            get {
                return ResourceManager.GetString("GettingParamsD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Getting updated parameters과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GettingUpdatedParams {
            get {
                return ResourceManager.GetString("GettingUpdatedParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Got param 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Gotparam {
            get {
                return ResourceManager.GetString("Gotparam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid home location과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Invalid_home_location {
            get {
                return ResourceManager.GetString("Invalid_home_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid Alt과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InvalidAlt {
            get {
                return ResourceManager.GetString("InvalidAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid BaudRate과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InvalidBaudRate {
            get {
                return ResourceManager.GetString("InvalidBaudRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid Board Type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InvalidBoardType {
            get {
                return ResourceManager.GetString("InvalidBoardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid Cert과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InvalidCert {
            get {
                return ResourceManager.GetString("InvalidCert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid Field과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InvalidField {
            get {
                return ResourceManager.GetString("InvalidField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid FileName과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InvalidFileName {
            get {
                return ResourceManager.GetString("InvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid number entered
        ///과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InvalidNumberEntered {
            get {
                return ResourceManager.GetString("InvalidNumberEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid Pan Range과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InvalidPanRange {
            get {
                return ResourceManager.GetString("InvalidPanRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid PortName과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InvalidPortName {
            get {
                return ResourceManager.GetString("InvalidPortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid Tilt Range과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InvalidTiltRange {
            get {
                return ResourceManager.GetString("InvalidTiltRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid Update Rate과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InvalidUpdateRate {
            get {
                return ResourceManager.GetString("InvalidUpdateRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Link Stats과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LinkStats {
            get {
                return ResourceManager.GetString("LinkStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load data과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Load_data {
            get {
                return ResourceManager.GetString("Load_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please click ok and move the autopilot around all axises in a circular motion과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MagCalibMsg {
            get {
                return ResourceManager.GetString("MagCalibMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mavlink Connecting...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MavlinkConnecting {
            get {
                return ResourceManager.GetString("MavlinkConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MavlinkSystemID {
            get {
                return ResourceManager.GetString("MavlinkSystemID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You are missing data points. do you want to run the calibration anyway?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MissingDataPoints {
            get {
                return ResourceManager.GetString("MissingDataPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Firmware과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NewFirmware {
            get {
                return ResourceManager.GetString("NewFirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New firmware available
        ///과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NewFirmwareA {
            get {
                return ResourceManager.GetString("NewFirmwareA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No firmware available for this board!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string No_firmware_available_for_this_board {
            get {
                return ResourceManager.GetString("No_firmware_available_for_this_board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No valid heartbeats read from port과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string No_valid_heartbeats_read_from_port {
            get {
                return ResourceManager.GetString("No_valid_heartbeats_read_from_port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No FMT message for 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NoFMTMessage {
            get {
                return ResourceManager.GetString("NoFMTMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No need to upload. already on the board과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NoNeedToUpload {
            get {
                return ResourceManager.GetString("NoNeedToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NO RC Receiver과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NORCReceiver {
            get {
                return ResourceManager.GetString("NORCReceiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not available when used as a windows store app과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Not_available_when_used_as_a_windows_store_app {
            get {
                return ResourceManager.GetString("Not_available_when_used_as_a_windows_store_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Note과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Obtain From Module과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ObtainFromModule {
            get {
                return ResourceManager.GetString("ObtainFromModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Onboard OSD과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string OnboardOSD {
            get {
                return ResourceManager.GetString("OnboardOSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Only 1 Heatbeat Received과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Only1Hb {
            get {
                return ResourceManager.GetString("Only1Hb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Only 1 Mavlink Heartbeat Packets was read from this port - Verify your hardware is setup correctly
        ///Mission Planner waits for 2 valid heartbeat packets before connecting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Only1HbD {
            get {
                return ResourceManager.GetString("Only1HbD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A Param refresh is required - Please press F5
        ///old #{0}  new #{1}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ParamRefreshRequired {
            get {
                return ResourceManager.GetString("ParamRefreshRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please connect first과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PleaseConnect {
            get {
                return ResourceManager.GetString("PleaseConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please connect and backup your config in the configuration tab.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PleaseConnectAndBackupConfig {
            get {
                return ResourceManager.GetString("PleaseConnectAndBackupConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please load a valid file과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PleaseLoadValidFile {
            get {
                return ResourceManager.GetString("PleaseLoadValidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select a cell first과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PleaseSelectCell {
            get {
                return ResourceManager.GetString("PleaseSelectCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please unplug the board, and then press OK and plug back in.
        ///Mission Planner will look for 30 seconds to find the board과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PleaseUnplugTheBoardAnd {
            get {
                return ResourceManager.GetString("PleaseUnplugTheBoardAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   
        ///Please upgrade과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Pleaseup {
            get {
                return ResourceManager.GetString("Pleaseup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please wait for the musical tones to finish before clicking OK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PleaseWaitForTheMusicalTones {
            get {
                return ResourceManager.GetString("PleaseWaitForTheMusicalTones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   pos horiz variance과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string pos_horiz_variance {
            get {
                return ResourceManager.GetString("pos_horiz_variance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   pos vert variance과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string pos_vert_variance {
            get {
                return ResourceManager.GetString("pos_vert_variance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucessfully programmed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ProgrammedOK {
            get {
                return ResourceManager.GetString("ProgrammedOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Put the transmitter in bind mode. Receiver is waiting.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Put_the_transmitter_in_bind_mode__Receiver_is_waiting {
            get {
                return ResourceManager.GetString("Put_the_transmitter_in_bind_mode__Receiver_is_waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string QuestionMark {
            get {
                return ResourceManager.GetString("QuestionMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Raw Param Warning과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RawParamWarning {
            get {
                return ResourceManager.GetString("RawParamWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All values on this screen are not min/max checked. Please double check your input.
        ///Please use Standard/Advanced Params for the safe settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RawParamWarningi {
            get {
                return ResourceManager.GetString("RawParamWarningi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reading Hex과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ReadingHex {
            get {
                return ResourceManager.GetString("ReadingHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reading Hex File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ReadingHexFile {
            get {
                return ResourceManager.GetString("ReadingHexFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Received List과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ReceivedList {
            get {
                return ResourceManager.GetString("ReceivedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   run anyway과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RunAnyway {
            get {
                return ResourceManager.GetString("RunAnyway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Saving과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scanning File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Scanning_File {
            get {
                return ResourceManager.GetString("Scanning_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select a comport과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SelectComport {
            get {
                return ResourceManager.GetString("SelectComport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set Here과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SetHere {
            get {
                return ResourceManager.GetString("SetHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show me again?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ShowMeAgain {
            get {
                return ResourceManager.GetString("ShowMeAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Standard Params과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StandardParams {
            get {
                return ResourceManager.GetString("StandardParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your model is still moving are you sure you want to disconnect?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Stillmoving {
            get {
                return ResourceManager.GetString("Stillmoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   terrain alt variance과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string terrain_alt_variance {
            get {
                return ResourceManager.GetString("terrain_alt_variance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This board has been retired, Mission Planner this will upload the last available version to your board (AC 3.2.1/AP 3.4.0)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ThisBoardHasBeenRetired {
            get {
                return ResourceManager.GetString("ThisBoardHasBeenRetired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Timeout waiting for autoscan/no mavlink device connected과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tracker Home과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TrackerHome {
            get {
                return ResourceManager.GetString("TrackerHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   trunk과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Trunk {
            get {
                return ResourceManager.GetString("Trunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   These are the latest trunk firmware, use at your own risk!!!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TrunkWarning {
            get {
                return ResourceManager.GetString("TrunkWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Trying to connect.
        ///Timeout in {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Trying {
            get {
                return ResourceManager.GetString("Trying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Units: {0}{1}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update Found
        ///
        ///Do you wish to update now? 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UpdateFound {
            get {
                return ResourceManager.GetString("UpdateFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No update available.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UpdateNotFound {
            get {
                return ResourceManager.GetString("UpdateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update Now과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UpdateNow {
            get {
                return ResourceManager.GetString("UpdateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Upload Complete과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UploadComplete {
            get {
                return ResourceManager.GetString("UploadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uploading {0} bytes to Board:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UploadingBytesToBoard {
            get {
                return ResourceManager.GetString("UploadingBytesToBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Upload succeeded, but verify failed: exp {0} got {1} at 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UploadSucceededButVerifyFailed {
            get {
                return ResourceManager.GetString("UploadSucceededButVerifyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   velocity variance과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string velocity_variance {
            get {
                return ResourceManager.GetString("velocity_variance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Verify Complete과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string VerifyComplete {
            get {
                return ResourceManager.GetString("VerifyComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Verify Firmware과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string VerifyFirmware {
            get {
                return ResourceManager.GetString("VerifyFirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning, as of AC 3.1 motors will spin when armed, configurable through the MOT_SPIN_ARMED parameter과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WarningAC31 {
            get {
                return ResourceManager.GetString("WarningAC31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning, if you are installing AC 3.2 for the first time you MUST redo a Compass calibration.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WarningAC32 {
            get {
                return ResourceManager.GetString("WarningAC32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log Browse will not function correctly without FMT messages in your log.
        ///These appear to be missing from your log.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WarningLogBrowseFMTMissing {
            get {
                return ResourceManager.GetString("WarningLogBrowseFMTMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning rally points are located greater than RALLY_LIMIT_KM과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Warningrallypointdistance {
            get {
                return ResourceManager.GetString("Warningrallypointdistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update Params
        ///DON&apos;T DO THIS IF YOU ARE IN THE AIR
        ///과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WarningUpdateParamList {
            get {
                return ResourceManager.GetString("WarningUpdateParamList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   loaded과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WpfileFileLoadText {
            get {
                return ResourceManager.GetString("WpfileFileLoadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You are using unsupported hardware.
        ///This board does not contain a valid certificate of authenticity.
        ///Please contact your hardware vendor about signing your hardware.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string YouAreUsingUnsupportedHardware {
            get {
                return ResourceManager.GetString("YouAreUsingUnsupportedHardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zoom To과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Zoom_To {
            get {
                return ResourceManager.GetString("Zoom_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zoom to the center or the loaded file?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Zoom_to_the_center_or_the_loaded_file {
            get {
                return ResourceManager.GetString("Zoom_to_the_center_or_the_loaded_file", resourceCulture);
            }
        }
    }
}
